# Generated by Django 2.1.7 on 2019-03-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restocking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='added',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, unique=True),
        ),
    ]
