# Generated by Django 2.1.7 on 2019-03-24 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restocking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsales',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='floor_quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, 'There is a value that is less than 0')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, 'There is a value that is less than 0')]),
        ),
        migrations.DeleteModel(
            name='ProductSales',
        ),
    ]
