# Generated by Django 2.1.7 on 2019-03-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restocking', '0002_auto_20190301_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restockinglist',
            old_name='restocking_list_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='restockinglist',
            name='restocking_list_time',
        ),
        migrations.AddField(
            model_name='restockinglist',
            name='time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
    ]
