# Generated by Django 2.1.7 on 2019-03-03 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restocking', '0003_auto_20190303_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='restockinglistitem',
            name='processed',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'There is a value that is less than 0')]),
        ),
    ]
