# Generated by Django 2.1.7 on 2019-03-24 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restocking', '0004_product_request_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='floor_quantity_from_request',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'There is a value that is less than 0')]),
        ),
    ]
