# Generated by Django 2.1.7 on 2019-03-06 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restocking', '0004_restockinglistitem_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='restockinglistitem',
            name='added',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='restocking.Order'),
        ),
        migrations.AlterField(
            model_name='restockinglist',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='restockinglistitem',
            name='restocking_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restocking_items', to='restocking.RestockingList'),
        ),
    ]
