# Generated by Django 2.1.7 on 2019-03-25 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restocking', '0005_product_floor_quantity_from_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='quantity_from_stock_room',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'There is a value that is less than 0')]),
        ),
    ]
