# Generated by Django 2.1.7 on 2019-03-06 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restocking', '0006_auto_20190306_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='restocking.Product'),
        ),
        migrations.AlterField(
            model_name='restockinglistitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_restocking_list', to='restocking.Product'),
        ),
    ]
