# Generated by Django 2.1.7 on 2019-03-11 10:22

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restocking', '0008_auto_20190306_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, 'There is a value that is less than 0')])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restocking.Product')),
            ],
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restocking.Product'),
        ),
    ]
