# Generated by Django 2.1.7 on 2019-03-13 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restocking', '0009_auto_20190311_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('[a-z]', 'Only lower case alphabet characters are allowed.')]),
        ),
    ]
