# Generated by Django 2.1.7 on 2019-03-13 14:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restocking', '0010_auto_20190313_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='restockinglist',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 13, 14, 0, 28, 904318, tzinfo=utc)),
        ),
    ]
