# Generated by Django 2.1.7 on 2019-03-13 14:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restocking', '0011_restockinglist_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 13, 14, 6, 5, 621249, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='restockinglist',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 13, 14, 6, 5, 622248, tzinfo=utc)),
        ),
    ]
