# Generated by Django 2.1.7 on 2019-03-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restocking', '0012_auto_20190313_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restockinglist',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
