# Generated by Django 2.1.7 on 2019-03-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restocking', '0013_auto_20190313_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsales',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
