# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-18 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restocking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NfcUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_identifier', models.CharField(max_length=3)),
            ],
        ),
    ]
