# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-15 17:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_processed', models.BooleanField(default=False)),
                ('order_delivered', models.BooleanField(default=False)),
                ('delivery_date', models.DateField(blank=True)),
                ('delivery_time', models.TimeField(blank=True)),
                ('delivery_processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'There is a value that is less than 1')])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restocking.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.DecimalField(choices=[(1, 1), (1.5, 1.5), (2, 2), (2.5, 2.5), (3, 3), (3.5, 3.5), (4, 4), (4.5, 4.5), (5, 5), (5.5, 5.5), (6, 6), (6.5, 6.5), (7, 7), (7.5, 7.5), (8, 8), (8.5, 8.5), (9, 9), (9.5, 9.5), (10, 10), (10.5, 10.5), (11, 11), (11.5, 11.5), (12, 12), (12.5, 12.5), (13, 13), (13.5, 13.5), (14, 14)], decimal_places=1, max_digits=4)),
                ('colour', models.CharField(max_length=20)),
                ('fitting', models.CharField(choices=[('d', 'D'), ('e', 'E'), ('f', 'F'), ('g', 'G'), ('h', 'H'), ('wide', 'Wide'), ('standard', 'Standard')], default='standard', max_length=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sale', models.BooleanField(default=False)),
                ('product_type', models.CharField(choices=[('shoe', 'Shoe'), ('boot', 'Boot'), ('sandal', 'Sandal'), ('slipper', 'Slipper')], max_length=10)),
                ('product_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('[A-Z]', 'Only capital alphabet characters are allowed.')])),
                ('department', models.CharField(choices=[('ladies', 'Ladies'), ('mens', 'Mens'), ('childrens', 'Childrens')], max_length=10)),
                ('floor_quantity', models.IntegerField(default=0)),
                ('stock_quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RestockingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restocking_list_date', models.DateField(auto_now=True)),
                ('restocking_list_time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestockingListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'There is a value that is less than 1')])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restocking.Product')),
                ('restocking_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restocking.RestockingList')),
            ],
        ),
        migrations.CreateModel(
            name='StockKeepingUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_limit', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1, 'There is a value that is less than 1')])),
            ],
        ),
        migrations.CreateModel(
            name='StockKeepingUnitItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_shelf', models.BooleanField(default=True)),
                ('sold', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restocking.Product')),
                ('stock_keeping_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restocking.StockKeepingUnit')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(auto_now=True)),
                ('transaction_time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'There is a value that is less than 1')])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restocking.Product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restocking.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restocking.User'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restocking.Product'),
        ),
    ]
