# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-24 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restocking', '0004_auto_20190224_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='restocking.Product'),
        ),
    ]
