# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-24 21:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restocking', '0005_auto_20190224_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='processed',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'There is a value that is less than 0')]),
        ),
    ]
